name: Setup Rust Environment
description: Setup mise, sccache, and cache cargo registry and target

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        echo "CARGO_HOME=${GITHUB_WORKSPACE}/.cargo" >> $GITHUB_ENV
        echo "CARGO_TARGET_DIR=${GITHUB_WORKSPACE}/src-tauri/target" >> $GITHUB_ENV
        echo "RUSTUP_HOME=${GITHUB_WORKSPACE}/.rustup" >> $GITHUB_ENV
        echo "PNPM_STORE_DIR=${GITHUB_WORKSPACE}/.pnpm-store" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_DIR=${GITHUB_WORKSPACE}/.sccache" >> $GITHUB_ENV
        echo "MISE_TRUSTED_CONFIG_PATHS=${GITHUB_WORKSPACE}/mise.toml" >> $GITHUB_ENV
        echo "MISE_VERBOSE=1" >> $GITHUB_ENV
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.6
    - name: Cache cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.CARGO_HOME }}/registry
          ${{ env.CARGO_HOME }}/git
          ${{ env.CARGO_TARGET_DIR }}
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ runner.os }}-
