#!/usr/bin/env bash

set -euo pipefail

function usage() {
  cat <<EOF

    Usage: $0 <command> [...args]

    Run a command in the "ci" container of docker compose.

EOF
  exit 1
}

if [[ $# == 0 ]] ; then
  usage
fi

USER_UID="$( id -u )"
export USER_UID
USER_GID="$( id -g )"
export USER_GID


exec docker compose run ci "$@"
